name: example
description: Example for the flutter_fancy_tree_view package.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.0.0

dependencies:
  faker: ^2.2.0
  flutter:
    sdk: flutter
  flutter_fancy_tree_view:
    path: ../
  path_drawing: ^1.0.1
  provider: ^6.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
