name: flutter_fancy_tree_view2
description: >
  A collection of widgets and slivers that helps bringing hierarchical data to life.
version: 1.6.1
homepage: https://alyssonpp.github.io/flutter_tree_view2/
repository: https://github.com/Alyssonpp/flutter_tree_view2

environment:
  sdk: ^3.1.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

screenshots:
  - description: A TreeView with lines connecting tree nodes.
    path: screenshots/connecting_lines.png
  - description: A TreeView with lines scoping the levels of tree nodes.
    path: screenshots/scoping_lines.png
  - description: A TreeView with blank indentations.
    path: screenshots/blank_indentation.png

topics:
  - layout
  - ui
